name: Run tests
on:
  push:
 
 
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./Dockerfile.ci
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Build docker images
      run: docker build -t main -f $COMPOSE_FILE .
 
    - name: Run tests
      run: docker run main